name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install deps
        run: yarn install
        env:
          CI: true

      - name: run tests
        run: yarn run test
        env:
          CI: true
